### ISSUE TITLE
CHECKOUT / Logistica en pago final Baleares / Peninsula

### ISSUE THREAD

**Issue by nika1983** [rockscripts/tienda_arriba#11]
Este punto estaba en el word , lo anoto aquí para no olvidarnos .

Contemplar que si hemos sacado el formulario de registro del popup , ahora al registro de la página si no estás logueado, te debe llevar a la pagina creada.

 Quitar los dólares que hay y poner €.

En envio debe sumar si la compra es en la península , a partir de 100€ gratis si es inferiror a 100 € sumarle 8 € por pedido.

En Baleares, a partir de 200 € gratis  si es menos de 200 € , 10 € por pedido

**Comment by rockscripts** [comment]
Actualiza precios para:
1. iniciar carrito, actualizar carrito.
2. Al cambiar direccion desde el checkout.
