### ISSUE TITLE
CHECKOUT / Dirección de envio DROPSHIPPING

### ISSUE THREAD

**Issue by nika1983** [rockscripts/tienda_arriba#15]
En el pago , en vez de salir la dirección que tenemos puesta, que es la que ponemos al registrarnos, debe aparecer una opción de poder cambiar esa dirección , por la de envio. pero no borrar la que ya tenemos registrada, que se almacenen las dos y poner la opcion de elegir la que se desee, ocrear una nueva dirección de envio.

**Comment by rockscripts** [comment]
Desarrollada para perfil y checkout
